config/urls.py
from django.contrib import admin
from django.urls import path, include
from inventario.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventario.urls')),
    path('users/', include('users.urls'))
]

inventario/urls.py
from django.urls import path
from . import views

app_name="inventario"

urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name="users"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.end_sesion, name="logout")
]

inventario/models.py
from django.db import models
from users.models import Company, Administrator

class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
class Providers(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
        
class Product(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    Units_available = models.IntegerField(default=0)
    price_by_unit = models.IntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
        
class Bill(models.Model):
    description = models.TextField()
    expedition_date = models.DateTimeField(auto_now_add=True)
    administrator = models.ForeignKey(Administrator, on_delete=models.CASCADE, related_name='bills_administrator')
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='bills_company')
    total_price = models.IntegerField()

    def __str__(self):
        mensaje = self.expedition_date+" "+self.total_price
        return mensaje
    
class Order(models.Model):

    OPCIONES_CLASIFICACION = [
        ('Venta', 'Venta'),
        ('Surtido', 'Surtido'),
    ]

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    products_units = models.IntegerField()
    total_price = models.IntegerField()
    administrator = models.ForeignKey(Administrator, on_delete=models.CASCADE, related_name='orders_administrator')
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='orders_company')
    type = models.CharField(max_length=10, choices=OPCIONES_CLASIFICACION)

    def __str__(self):
        mensaje = self.product.name+" "+self.products_units+" "+self.total_price+" "+self.type
        return mensaje
    
    def type_order(self):
        return self.type=='Venta'

users/models.py
from django.db import models
from django.contrib.auth.models import User

class Company(models.Model):
    name = models.CharField(max_length=50, unique=True)
    sales_balance = models.IntegerField(default=0)
    inventory_balance = models.IntegerField(default=0)

    def __str__(self):
        return self.name



class Administrator(User):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    def __str__(self):
        return self.username

inventario/views.py
from django.shortcuts import render, HttpResponse
# proteccion de rutas 
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request,"index.html")


def home(request):
    return render(request,"home.html")

users/views.py
# manejo de rutas 
from django.shortcuts import render, redirect
from users.models import Administrator, Company

# registro y autenticacion de usuarios 
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError

# proteccion de rutas 
from django.contrib.auth.decorators import login_required

# registro
def signup(request):
    if request.method=="GET":
        return render(request,"users/register.html")
    else:
        # verificamos que las contraseñas coincidan
        if request.POST["password1"] == request.POST["password2"]:
            try:
                # registramos al empresa 
                new_company = Company.objects.create(
                    name = request.POST["name_company"]
                )
                # registramos el usuario nuevo 
                new_user = Administrator.objects.create(
                    first_name=request.POST["first_name"],
                    last_name=request.POST["last_name"],
                    email=request.POST["email"],
                    username=request.POST["username"], 
                    password=request.POST["password1"],
                    company = new_company
                )
                new_user.save()
                # le damos un login automantico al usuario 
                login(request,new_user)
                print("registrado")
                return redirect("inventario:home")
            # en caso de que el usuario o empresa ya esten registrado elevamos el error de integridad 
            except IntegrityError: 
                print("ya existe")
                return render(request,"users/register.html",{
                    "mensaje":"username o empresa ya existente "
                })
        print("contraseñas erroneas ")
        return render(request,"users/register.html",{
            "mensaje":"las contraseñas no coinciden "
        })

# autenticacion y login
def login_(request):
    if request.method=="GET":
        return render(request,"users/login.html")
    else:
        user = authenticate(
            request, 
            username = request.POST["username"], 
            password = request.POST["password"])
        if user == None:
            return render(request,"users/login.html",{
            "mensaje":" Credenciales incorrectas"
        })
        else:
            login(request,user)
            return redirect("inventario:home")






@login_required
def end_sesion(request):
    logout(request)
    return redirect("users:signin")

inventario/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <title>Inventory</title>
  </head>

  <body>    
        <!-- contenedor de secciones  -->
        <div class="col section-container px-0 align-items-center justify-content-center">
        {% block content %}
                {% block page_content %}{% endblock %}
        {% endblock %}
        </div>
    </div>
      
      
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    </body>
</html>

inventario/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block page_content %}

<div class="container py-4">
    
    <!-- panel de control  -->
    <div class="p-5 mb-4 rounded-3 fr">
      <div class="container-fluid py-3">

        <div class="row ">
          <div class="col-sm-8">
            <h1 class="fw-bold display-1 mb-3">Empresa</h1>
          </div>
          <div class="col-sm-4">col-sm-4</div>
        </div>
        <div class="row">
          <div class="col-sm">
            <p class="fw-bold display-6 mb-2">Total</p>
            <h2 class="fw-bold t_balance">2,456.450</h2>
          </div>
          <div class="col-sm">
            <p class="fw-bold display-6 mb-2">Ventas</p>
            <h2 class="fw-bold t_balance">2,456.450</h2>
          </div>
          <div class="col-sm">
            <p class="fw-bold display-6 mb-2">Inventario</p>
            <h2 class="fw-bold t_balance">2,456.450</h2>
          </div>
        </div>

      </div>
    </div>

    <div class="row align-items-md-stretch">

      <!-- listado de Productos  -->
      <div class="col-md-6 mb-3">
        <div class="h-100 p-5 rounded-3 fr">
          <h2 class="fw-bold mb-2">Productos</h2>
          <ul class="list-group  text-light">
            <a href="">
              <li class=" rounded-3 mb-2 p-3 d-flex justify-content-between lh-sm porduct_item">
                <div>
                  <h6 class="text-light">Product name</h6>
                  <small class="">Unidades disponibles</small>
                </div>
                <span class="">$12</span>
              </li>
            </a>
            <a href="">
              <li class=" rounded-3 mb-2 p-3 d-flex justify-content-between lh-sm porduct_item">
                <div>
                  <h6 class="text-light">Product name</h6>
                  <small class="">Unidades disponibles</small>
                </div>
                <span class="">$12</span>
              </li>
            </a>
            <a href="">
              <li class=" rounded-3 mb-2 p-3 d-flex justify-content-between lh-sm porduct_item">
                <div>
                  <h6 class="text-light">Product name</h6>
                  <small class="">Unidades disponibles</small>
                </div>
                <span class="">$12</span>
              </li>
            </a>
            <a href="">
              <li class=" rounded-3 mb-2 p-3 d-flex justify-content-between lh-sm porduct_item">
                <div>
                  <h6 class="text-light">Product name</h6>
                  <small class="">Unidades disponibles</small>
                </div>
                <span class="">$12</span>
              </li>
            </a>
            <a href="">
              <li class=" rounded-3 mb-2 p-3 d-flex justify-content-between lh-sm porduct_item">
                <div>
                  <h6 class="text-light">Product name</h6>
                  <small class="">Unidades disponibles</small>
                </div>
                <span class="">$12</span>
              </li>
            </a>
            <a href="">
              <li class=" rounded-3 mb-2 p-3 d-flex justify-content-between lh-sm porduct_item">
                <div>
                  <h6 class="text-light">Product name</h6>
                  <small class="">Unidades disponibles</small>
                </div>
                <span class="">$12</span>
              </li>
            </a>
            
           
          </ul>
          <button class="btn  p-2 mb-1 btr" type="button">Example button</button>
        </div>
      </div>

      <div class="col-md-6 mb-3">
        <div class="h-100 pt-0 rounded-3 ">
          <div class="container ">

            <!-- seccion de categorias -->
            <div class="row mb-3 pt-0 h-40 fr rounded-3">
              <div class="col p-5  h-100 ">
                <h2>Categorias</h2>
                <div class="container text-light text-center mb-2">
                  <div class="row ">
                    <div class="col border m-2 rounded-3 p-2">
                      Categoria
                    </div>
                    <div class="col border m-2 rounded-3 p-2">
                      Categoria
                    </div>
                    <div class="col border m-2 rounded-3 p-2">
                      Categoria
                    </div>
                    <div class="col border m-2 rounded-3 p-2">
                      Categoria
                    </div>
                    <div class="col border m-2 rounded-3 p-2">
                      Categoria
                    </div>
                    <div class="col border m-2 rounded-3 p-2">
                      Categoria
                    </div>
                    <div class="col border m-2 rounded-3 p-2">
                      Categoria
                    </div>
                  </div>
                </div>
                <button class="btn  mt-3 btr" type="button">Example button</button>
              </div>
            </div>

            <!-- seccion de proveedores  -->
            <div class="row fr h-40 pb-0 rounded-3">
              <div class="col p-5 ">
                <h2>Proveedores</h2>
                <div class="container text-light text-center mb-2">
                  <div class="row ">
                    <div class="col border m-2 rounded-3 p-2">
                      Proveedor
                    </div>
                    <div class="col border m-2 rounded-3 p-2">
                      Proveedor
                    </div>
                    <div class="col border m-2 rounded-3 p-2">
                      Proveedor
                    </div>
                    <div class="col border m-2 rounded-3 p-2">
                      Proveedor
                    </div>
                    <div class="col border m-2 rounded-3 p-2">
                      Proveedor
                    </div>
                    <div class="col border m-2 rounded-3 p-2">
                      Proveedor
                    </div>
                  </div>
                </div>
                <button class="btn mt-3 btr" type="button">Example button</button>
              </div>
            </div>

          </div>
        </div>
      </div>
      
    </div>

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5  rounded-3 fr">
          <h2>Change the background</h2>
          <p>Swap the background-color utility and add a `.text-*` color utility to mix up the jumbotron look. Then, mix and match with additional component themes and more.</p>
          <button class="btn btn-outline-light" type="button">Example button</button>
        </div>
      </div>
      <div class="col-md-6 ">
        <div class="h-100 p-5   rounded-3 fr">
          <h2>Add borders</h2>
          <p>Or, keep it light and add a border for some added definition to the boundaries of your content. Be sure to look under the hood at the source HTML here as we've adjusted the alignment and sizing of both column's content for equal-height.</p>
          <button class="btn btn-outline-secondary" type="button">Example button</button>
        </div>
      </div>
    </div>

</div>

{% endblock %}

inventario/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block page_content %}

    
  <div class="container col-xl-10 col-xxl-8 px-4 py-1">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
      <div class="col-10 col-sm-8 col-lg-6">
        <h1 class="display-5 fw-bold  lh-1 text-body-emphasis mb-3">Gestiona tu negocio de manera eficiente y sencilla</h1>
        <p class="lead col-lg-10 fs-4">Inventory es una plataforma integral diseñada para ayudarte a mantener un control total sobre el inventario, cuentas, presupuesto y estadísticas de tu negocio, todo en un solo lugar.</p>
      </div>
      <div class="col-lg-6">
        <img src="{% static 'img/heder_image.png' %}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
      </div>
    </div>
  </div>

  <div class="container col-xl-10 col-xxl-8 px-4 py-1">
    <div class="row align-items-center g-lg-5 py-5">
      <div class="col-lg-7 text-center text-lg-start ">
        <h1 class="display-4 fw-bold lh-1 text-body-emphasis mb-3">Inicia sesion o registrate ahora </h1>
        <p class="col-lg-10 fs-4">¡Regístrate ahora y lleva tu negocio al siguiente nivel con Inventory! Nuestra plataforma intuitiva y completa te ayudará a simplificar la gestión de tu inventario, cuentas, presupuesto y estadísticas. Únete a nuestra comunidad de empresarios exitosos y descubre cómo puedes optimizar tus operaciones comerciales en un solo lugar.</p>
      </div>
      <div class="col-md-10 mx-auto col-lg-5">
        <form action="{% url 'users:login' %}" method="post" class="p-4 p-md-5 text-white rounded-3  fr">
          {% csrf_token %}
          <div class="form-floating mb-3">
            <input type="text" class="form-control bg-secondary border-0 text-white" id="floatingInput" placeholder="name@example.com" required>
            <label for="floatingInput">Usename</label>
          </div>
          <div class="form-floating mb-3">
            <input type="password" class="form-control bg-secondary border-0 text-white" id="floatingPassword" placeholder="Password" required>
            <label for="floatingPassword">Password</label>
          </div>
          <div class="checkbox mb-3">
            <label>
              <input class="text-white" type="checkbox" value="remember-me"> Remember me
            </label>
          </div>
          
          <button class="w-100 btn btn-lg  mb-3 btl" type="submit" >Login</button>
          <a href="{% url 'users:signup' %}" class="w-100 btn btn-lg  mb-3 btr">Registrarme
          </a>
        </form>
      </div>
    </div>
  </div>


  <div class="container col-xl-10 col-xxl-8 px-4 py-1" id="featured-3">
    <h2 class="pb-2 border-bottom">Columns with icons</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
      <div class="feature col">
        <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
          <svg class="bi" width="1em" height="1em"><use xlink:href="#collection"/></svg>
        </div>
        <h3 class="fs-2 text-body-emphasis">Featured title</h3>
        <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
        <a href="#" class="icon-link">
          Call to action
          <svg class="bi"><use xlink:href="#chevron-right"/></svg>
        </a>
      </div>
      <div class="feature col">
        <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
          <svg class="bi" width="1em" height="1em"><use xlink:href="#people-circle"/></svg>
        </div>
        <h3 class="fs-2 text-body-emphasis">Featured title</h3>
        <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
        <a href="#" class="icon-link">
          Call to action
          <svg class="bi"><use xlink:href="#chevron-right"/></svg>
        </a>
      </div>
      <div class="feature col">
        <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
          <svg class="bi" width="1em" height="1em"><use xlink:href="#toggles2"/></svg>
        </div>
        <h3 class="fs-2 text-body-emphasis">Featured title</h3>
        <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
        <a href="#" class="icon-link">
          Call to action
          <svg class="bi"><use xlink:href="#chevron-right"/></svg>
        </a>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block page_content %}

  <div class="modal modal-sheet position-static d-block p-4 py-md-5 " tabindex="-1" role="dialog" id="modalSignin">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-4 shadow fr text-white">
        <div class="modal-header p-5 pb-4 border-bottom-0 ">
          <h1 class="fw-bold mb-0 fs-2">Inicia sesion ahora</h1>
        </div>
  
        <div class="modal-body p-5 pt-0">
          <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            <div class="form-floating mb-3">
              <input type="text" name="username" class="form-control rounded-3 bg-secondary border-0 text-white" id="floatingInput" placeholder="name@example.com" required>
              <label for="floatingInput">Username</label>
            </div>
            <div class="form-floating mb-3">
              <input type="password" name="password" class="form-control rounded-3 bg-secondary border-0 text-white" id="floatingPassword" placeholder="Password" required>
              <label for="floatingPassword">Password</label>
            </div>
            <div class="checkbox mb-3">
              <label>
                <input class="text-white" type="checkbox" value="remember-me"> Remember me
              </label>
            </div>
            
            <button class="w-100 btn btn-lg  mb-3 btl" type="submit" >Login</button>
            
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}
{% load static %}

{% block page_content %}

<div class="modal modal-sheet position-static d-block p-4 py-md-5 " tabindex="-1" role="dialog" id="modalSignin">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-4 shadow fr text-white">
        <div class="modal-header p-5 pb-4 border-bottom-0 ">
          <h1 class="fw-bold mb-0 fs-2">Registrate ahora</h1>
        </div>
  
        <div class="modal-body p-5 pt-0">
          <form action="{% url 'users:signup' %}" method="post">
            {% csrf_token %}
            <div class="form-floating mb-3">
              <input type="text" name="name_company" class="form-control rounded-3 bg-secondary border-0 text-white" id="floatingInput" placeholder="name@example.com" required>
              <label for="floatingInput">Nombre de tu empresa</label>
            </div>

            <h3>Adminsitrador</h3>
            <div class="form-floating mb-3">
                <input type="text" name="first_name" class="form-control rounded-3 bg-secondary border-0 text-white" id="floatingInput" placeholder="name@example.com" required>
                <label for="floatingInput">Nombre</label>
              </div>

              <div class="form-floating mb-3">
                <input type="text" name="last_name" class="form-control rounded-3 bg-secondary border-0 text-white" id="floatingInput" placeholder="name@example.com" required>
                <label for="floatingInput">Apellido</label>
              </div>
              <div class="form-floating mb-3">
                <input type="email" name="email" class="form-control rounded-3 bg-secondary border-0 text-white" id="floatingInput" placeholder="name@example.com" required>
                <label for="floatingInput">Email</label>
              </div>
            
            <h3>Credenciales</h3>
            <div class="form-floating mb-3">
                <input type="text"  name="username" class="form-control rounded-3 bg-secondary border-0 text-white" id="floatingPassword" placeholder="Password" required>
                <label for="floatingPassword">Username</label>
              </div>
            <div class="form-floating mb-3">
                <input type="password"  name="password1" class="form-control rounded-3 bg-secondary border-0 text-white" id="floatingPassword" placeholder="Password" required>
                <label for="floatingPassword">Password</label>
              </div>
            <div class="form-floating mb-3">
              <input type="password" name="password2" class="form-control rounded-3 bg-secondary border-0 text-white" id="floatingPassword" placeholder="Password" required>
              <label for="floatingPassword">Repetir Password</label>
            </div>

            
            <button class="w-100 btn btn-lg  mb-3 btr" type="submit" >Registrarme</button>
            
          </form>
        </div>
      </div>
    </div>
  </div>
    

{% endblock %}